[package]
name = "vvvst-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["xtask"]

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug_webview = { git = "https://github.com/maxjvh/nih-plug-webview.git" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0"
